notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - python3 setup.py install || python setup.py install
  - pip3 install codecov
  - pip3 install coveralls

# commands to run tests
script:
  # open app from CLI
  - color-space-converter -h
  # trigger unit tests and code coverage
  - python3 -m coverage run test/unit_test.py || python -m coverage run test/unit_test.py
  - coveralls

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pip3 install --upgrade twine;
      python3 setup.py sdist bdist_wheel;
      python3 -m twine upload --repository https://test.pypi.org/legacy/ dist/* -u __token__ -p $TEST_PYPI;
      python3 -m pip install --index-url https://test.pypi.org/simple/ color-space-converter;
    fi

deploy:
  - provider: pypi
    user: __token__
    skip_cleanup: true
    skip_existing: true
    distributions: sdist bdist_wheel
    server: https://upload.pypi.org/legacy/
    password:
      secure: Qt/nSs2T81zgFBfLOMQPmhDFn+o8W+l12VxIalAwtVTFv2J5Z9MJjqq/XobRLgv9UST/BOpMRuAaIpdOohejVR4bgOXbZeG1HxVkx1cUOfWTVl+t9ZfACVRFMBeCcIcZezsFYD4CbbV/5WU5hB/GIBds83Iu4LuILDacqCHFQSNCFvFqXhauQHADHhk4qth1z9lISjB/RQQYy3bnAtW9q81xpA0YLg8jjaa8jWw9To/UlOjxNjA6umC77yjm+H77Dz5PRBUqeKKWzfG0u527CUOEdETZ3Prd06q0gzvPEsFG/6FgaqjhWPgsUo5pMr0zFmxGxLOGk3etjJm6hjUPd0y8q/tiB73EGp+ZLXu6IJvFYSmNn/QPIhWmqUs40aKpoGH/ESrFsIaTls5WWTGCBkLZJg3MyiaREL9xI2ZzMxric36lLnc+MYmY5tATqRwzDWUsFwCQobHCWbZEaYa/v6P1imhSWEzjM+kQq0hbpd9kQf2Eg0hpxI3SWfee3cHHhvSm7WEdKBhdytPymIXtWRFx2KOh8mXn6fpZ3PI2W50cARupFWG5zQwi5Jgqncb9Bg8BQuHiWwQtCnMqhlDWnuFfLBrXtrXhtqzG5U0+PNlbQzTwyz0bLpPxHyDaAL/aQ4JTMM/JpWkwmXK9iCtHkNkjfloR1Q/hCe1WueQj5LM=
    on:
      condition: $TRAVIS_OS_NAME = linux
      branches:
        only:
          - master

  - provider: releases
    name: Release $TRAVIS_TAG
    skip_cleanup: true
    api_key:
      secure: yGvHWhi42KG8tlhFMTBIBAURS/mNY97J5vw3cpF7tVyxywa4Lfk5XtDd6a0nuRLgchmugl8957nSCiNZSIVKfF7r5Lo/UzOS0+uFqZAtHSCncLrnxx/DlDEDN1vFOZQ7xRMHDYc9SvTkzHhntpzR6jAqdynIU2NpPGq2jcYs0H5WeUV/ItRLXWXoOYz5SbjQgdPk1d9Z2Mkifv1vwfvt60vPGQEEGKkxl2PV0KTD1JyUohlyjhmdoB8NOyJ4EzppKFHbufsTbuOdXu1pSb1BZYCDpDoRxsMHnO0MC2x3IqK9QpkaWyIg8c9wqY2Twd9bKv6X+yZ/1Ik8vMt2gRHpB+RTkhTdsgIhPC2ubr4IeZqamxwiV2sLRw/wFwPSG4ptw7UO/9BxTz8LxslL7ImakSRiB9JkzeFGcww9UCM+h5diKkFhOaHemADhpZ+V4tfwKVxfBydas6ND+r+5Tg4Ptyxg0BxDcYbgLeo/uZVy5td6XjiZOOkAIUZclJ4qLOLRv09ICL1PTckCUUAsyegVWipfg7quMWZtzezMQt/hv1HYOnpPbgRJPp3EZdMSFS05U3IUAdnliFgDsUyMYw00Vk4G5ER0tgcLgCeYvrz1250kCfx/JpeVJrz1lA13z/5mpLglVxzJJ31ys6npcm4KntHWp270ZbytivqOfXONbQc=
    file_glob: true
    file:
      - dist/*.whl
      - dist/*.tar.gz
      - dist/*.egg
    draft: true
    on:
      repo: hahnec/color-space-converter
      condition: $TRAVIS_OS_NAME = linux
      branches:
        only:
          - master